In [ ]:
 import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression

In [ ]:
#1.  Загрузить датасет (из Kaggle или другого источника) и вывести первые 10 строк.
df = pd.read_csv('/content/StudentsPerformance.csv')
df.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50

In [ ]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [ ]:
df .shape

(1000, 8)

In [ ]:
df .describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [ ]:
df.dtypes
#3.  Вывести список колонок и их типы.

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

In [ ]:
#4.  Проверить на пропущенные значения.
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [ ]:
#51.  Закодировать категориальные переменные (LabelEncoder или OneHot)
df = pd.get_dummies(df, columns = ['gender',  'race/ethnicity',
                              'parental level of education',
                              'lunch',  'test preparation course'],
               drop_first=True).astype(int)

In [ ]:
#52.  Нормализовать числовые признаки (StandardScaler).

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
features = df.drop(columns=('writing score'))
scaled_data = scaler.fit_transform(features)

In [ ]:
#54.  Разделить X и y (y = math score).
x = scaled_data
y = df['writing score']

In [ ]:
#55.  Сделать train/test split (80/20).
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
#56.  Построить LinearRegression() модель.
lin_model = LinearRegression()

In [ ]:
#57.  Обучить модель на тренировочных данных.
lin_model.fit(x_train, y_train)

LinearRegression()

In [ ]:
#58.  Предсказать на тестовой выборке.
y_pred = lin_model.predict(x_test)

In [ ]:
#59.  Вычислить метрики: MAE, MSE, RMSE, R².
from sklearn.metrics import r2_score

r2_score(y_test, y_pred)

0.9381328994057507

In [ ]:
import joblib

joblib.dump(lin_model, 'model.pkl')
joblib.dump(scaler, 'scaler.pkl')

['scaler.pkl']